<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQF0P95S\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQF0P95S/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQF0P95S.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQF0P95S\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQF0P95S\App_KernelDevDebugContainer([
    'container.build_hash' => 'QF0P95S',
    'container.build_id' => 'd7d667c1',
    'container.build_time' => 1667411152,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQF0P95S');
