<?php

namespace ContainerAj6dLxz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H7qzkVEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h7qzkVE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h7qzkVE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comment' => ['privates', '.errored..service_locator.h7qzkVE.App\\Entity\\Comment', NULL, 'Cannot autowire service ".service_locator.h7qzkVE": it references class "App\\Entity\\Comment" but no such service exists.'],
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
        ], [
            'comment' => 'App\\Entity\\Comment',
            'commentRepository' => 'App\\Repository\\CommentRepository',
        ]);
    }
}
