<?php

namespace ContainerAj6dLxz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComment2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.h7qzkVE.App\Entity\Comment' shared service.
     *
     * @return \App\Entity\Comment
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.h7qzkVE": it references class "App\\Entity\\Comment" but no such service exists.');
    }
}
