<?php

namespace ContainerQF0P95S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9b2VBJEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9b2VBJE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9b2VBJE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminSecurityContollerController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\ApiArticleController::index' => ['privates', '.service_locator.flUxzNK', 'get_ServiceLocator_FlUxzNKService', true],
            'App\\Controller\\ApiArticleController::show' => ['privates', '.service_locator.7ttFu3o', 'get_ServiceLocator_7ttFu3oService', true],
            'App\\Controller\\ApiCommentController::comments' => ['privates', '.service_locator.joHrCtt', 'get_ServiceLocator_JoHrCttService', true],
            'App\\Controller\\ArticleController::delete' => ['privates', '.service_locator.Ah80EsV', 'get_ServiceLocator_Ah80EsVService', true],
            'App\\Controller\\ArticleController::edit' => ['privates', '.service_locator.Ah80EsV', 'get_ServiceLocator_Ah80EsVService', true],
            'App\\Controller\\ArticleController::index' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\ArticleController::new' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\ArticleController::show' => ['privates', '.service_locator.ewTmbP1', 'get_ServiceLocator_EwTmbP1Service', true],
            'App\\Controller\\CommentController::delete' => ['privates', '.service_locator.h7qzkVE', 'get_ServiceLocator_H7qzkVEService', true],
            'App\\Controller\\CommentController::edit' => ['privates', '.service_locator.h7qzkVE', 'get_ServiceLocator_H7qzkVEService', true],
            'App\\Controller\\CommentController::index' => ['privates', '.service_locator.BwLcYXx', 'get_ServiceLocator_BwLcYXxService', true],
            'App\\Controller\\CommentController::new' => ['privates', '.service_locator.BwLcYXx', 'get_ServiceLocator_BwLcYXxService', true],
            'App\\Controller\\CommentController::show' => ['privates', '.service_locator.CbsAoJ.', 'get_ServiceLocator_CbsAoJ_Service', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.nWpr6Po', 'get_ServiceLocator_NWpr6PoService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdminSecurityContollerController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\ApiArticleController:index' => ['privates', '.service_locator.flUxzNK', 'get_ServiceLocator_FlUxzNKService', true],
            'App\\Controller\\ApiArticleController:show' => ['privates', '.service_locator.7ttFu3o', 'get_ServiceLocator_7ttFu3oService', true],
            'App\\Controller\\ApiCommentController:comments' => ['privates', '.service_locator.joHrCtt', 'get_ServiceLocator_JoHrCttService', true],
            'App\\Controller\\ArticleController:delete' => ['privates', '.service_locator.Ah80EsV', 'get_ServiceLocator_Ah80EsVService', true],
            'App\\Controller\\ArticleController:edit' => ['privates', '.service_locator.Ah80EsV', 'get_ServiceLocator_Ah80EsVService', true],
            'App\\Controller\\ArticleController:index' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\ArticleController:new' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\ArticleController:show' => ['privates', '.service_locator.ewTmbP1', 'get_ServiceLocator_EwTmbP1Service', true],
            'App\\Controller\\CommentController:delete' => ['privates', '.service_locator.h7qzkVE', 'get_ServiceLocator_H7qzkVEService', true],
            'App\\Controller\\CommentController:edit' => ['privates', '.service_locator.h7qzkVE', 'get_ServiceLocator_H7qzkVEService', true],
            'App\\Controller\\CommentController:index' => ['privates', '.service_locator.BwLcYXx', 'get_ServiceLocator_BwLcYXxService', true],
            'App\\Controller\\CommentController:new' => ['privates', '.service_locator.BwLcYXx', 'get_ServiceLocator_BwLcYXxService', true],
            'App\\Controller\\CommentController:show' => ['privates', '.service_locator.CbsAoJ.', 'get_ServiceLocator_CbsAoJ_Service', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.nWpr6Po', 'get_ServiceLocator_NWpr6PoService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdminSecurityContollerController::login' => '?',
            'App\\Controller\\ApiArticleController::index' => '?',
            'App\\Controller\\ApiArticleController::show' => '?',
            'App\\Controller\\ApiCommentController::comments' => '?',
            'App\\Controller\\ArticleController::delete' => '?',
            'App\\Controller\\ArticleController::edit' => '?',
            'App\\Controller\\ArticleController::index' => '?',
            'App\\Controller\\ArticleController::new' => '?',
            'App\\Controller\\ArticleController::show' => '?',
            'App\\Controller\\CommentController::delete' => '?',
            'App\\Controller\\CommentController::edit' => '?',
            'App\\Controller\\CommentController::index' => '?',
            'App\\Controller\\CommentController::new' => '?',
            'App\\Controller\\CommentController::show' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminSecurityContollerController:login' => '?',
            'App\\Controller\\ApiArticleController:index' => '?',
            'App\\Controller\\ApiArticleController:show' => '?',
            'App\\Controller\\ApiCommentController:comments' => '?',
            'App\\Controller\\ArticleController:delete' => '?',
            'App\\Controller\\ArticleController:edit' => '?',
            'App\\Controller\\ArticleController:index' => '?',
            'App\\Controller\\ArticleController:new' => '?',
            'App\\Controller\\ArticleController:show' => '?',
            'App\\Controller\\CommentController:delete' => '?',
            'App\\Controller\\CommentController:edit' => '?',
            'App\\Controller\\CommentController:index' => '?',
            'App\\Controller\\CommentController:new' => '?',
            'App\\Controller\\CommentController:show' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
